[Header]
2011-11-16 09:46:25,755 [8488] DEBUG ConsoleApp.LoggingExample [(null)] - This is a debug message
2011-11-16 09:46:25,771 [8488] ERROR ConsoleApp.LoggingExample [(null)] - Exception thrown from method Bar
System.ArithmeticException: Failed in Goo. Calling Foo. Inner Exception provided ---> System.Exception: This is an Exception
   at ConsoleApp.LoggingExample.Foo() in C:\temp\Log4Net_1.2.11\log4net-1.2.11\examples\net\2.0\Tutorials\ConsoleApp\cs\src\ConsoleApplication1\LoggingExample.cs:line 97
   at ConsoleApp.LoggingExample.Goo() in C:\temp\Log4Net_1.2.11\log4net-1.2.11\examples\net\2.0\Tutorials\ConsoleApp\cs\src\ConsoleApplication1\LoggingExample.cs:line 104
   --- End of inner exception stack trace ---
   at ConsoleApp.LoggingExample.Goo() in C:\temp\Log4Net_1.2.11\log4net-1.2.11\examples\net\2.0\Tutorials\ConsoleApp\cs\src\ConsoleApplication1\LoggingExample.cs:line 110
   at ConsoleApp.LoggingExample.Bar() in C:\temp\Log4Net_1.2.11\log4net-1.2.11\examples\net\2.0\Tutorials\ConsoleApp\cs\src\ConsoleApplication1\LoggingExample.cs:line 92
   at ConsoleApp.LoggingExample.Main(String[] args) in C:\temp\Log4Net_1.2.11\log4net-1.2.11\examples\net\2.0\Tutorials\ConsoleApp\cs\src\ConsoleApplication1\LoggingExample.cs:line 58
[Footer]
